language: cpp
sudo: required
dist: trusty

install:
  - >
    ./tools/travis-install.sh
    ${host:+--host="${host}"}
    ${flavour:+--flavour="${flavour}"}

script:
  - >
    ./tools/travis-build.sh
    ${host:+--host="${host}"}
    ${flavour:+--flavour="${flavour}"}
    ${scan_build:+--scan-build}
    $opts

compiler: gcc
env:
  - ""
  - flavour=Debug scan_build=yes
  - host=i686-linux-gnu
  - flavour=Debug host=i686-w64-mingw32 scan_build=yes
  - host=x86_64-w64-mingw32

# One extra build with clang, its warnings are often better
matrix:
  include:
    - compiler: clang
      env: flavour=Debug scan_build=yes
